### ISSUE TITLE
Doesnt work with mcc-island

### ISSUE THREAD

**Issue by OmegaPhoenix637** [DrTheodor/rptweaks#1]
It breaks with mcci, I can't join the server with this mod installed

**Comment by drtheodor** [comment]
Hello! I just tested it, and it seems to work fine... Can you describe what's wrong more specifically? What's your Minecraft version?

**Comment by drtheodor** [comment]
Does it crash your Minecraft when you log on the server? Or the server kicks you because it fails to apply the pack?

**Comment by drtheodor** [comment]
Does the server kick message look like this by any chance?
![image](https://github.com/DrTheodor/rptweaks/assets/71725814/5868949b-80c1-4378-b11d-64acf2f98722)

**Comment by OmegaPhoenix637** [comment]
Minecraft version 1.20.1, yea I got that error message, It happened when I logged onto the server and hopped off and restarted my minecraft. It only happened after a few times. The issue was not a crash, but I couldn't log onto mcci cuz that kick message. It worked fine before that. Sorry for the lack of information in my first comment :\

**Comment by drtheodor** [comment]
Is this option set as "Enabled"?
![image](https://github.com/DrTheodor/rptweaks/assets/71725814/7ca0f299-bb34-4f70-a3b6-a02fcd65a78c)

**Comment by OmegaPhoenix637** [comment]
Yea, and if I don’t enable it than it will ask in game to enable it and kicks after that

**Comment by drtheodor** [comment]
Huh, thats weird... I suppose you didnt change the mod's config? 
I have 2 theories on what could be wrong:
1. Downloaded zip file got corrupted
2. Mod's config got corrupted

Can you send me the mod's config? (`.minecraft/config/rptweaks.properties`)

**Comment by OmegaPhoenix637** [comment]
found the config this is in it :
#If true, makes Minecraft load the latest pack before launch.
#preload: (true|false)
#
#Sat Aug 12 20:05:30 CEST 2023
preload=true
latest=f27e50e9b8ef6286d1167409de3ccf33aae49361
also downloaded the file for the second time from modrinth and still the same

**Comment by drtheodor** [comment]
Hmm, try deleting the config, and if it stops working again, please send me the logs

**Comment by OmegaPhoenix637** [comment]
error with logging into mcci 
Connecting to play.mccisland.net, 25565
net.minecraft.class_1066
Netty Client IO #6
.minecraft\server-resource-packs\f27e50e9b8ef6286d1167409de3ccf33aae49361 matching requested hash a703a5ce8051e8926bbd1d7bef6397119f7a6357
net.minecraft.class_634
Render thread
Ignoring player info update for unknown player `playerid`
Netty Client IO #6
.minecraft\server-resource-packs\f27e50e9b8ef6286d1167409de3ccf33aae49361 matching requested hash a703a5ce8051e8926bbd1d7bef6397119f7a6357

deleting config changes nothing 

and if you install modmenu it will give this error:

Mod rptweaks provides a broken implementation of ModMenuApi
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_327.method_27525(net.minecraft.class_5348)" because "net.minecraft.class_310.method_1551().field_1772" is null
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.<init>(BooleanListEntry.java:75)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder$1.<init>(BooleanToggleBuilder.java:101)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder.build(BooleanToggleBuilder.java:101)
	at dev.drtheo.rptweaks.modmenu.RPTweaksMenu.getModConfigScreenFactory(RPTweaksMenu.java:26)
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:70)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Mod Menu/Update Checker
Worker-Main-1
Checking mod updates...

net.minecraft.class_310
Render thread
Backend library: LWJGL version 3.3.1 SNAPSHOT

net.minecraft.class_156
Worker-Main-1
Caught exception in thread Thread[Worker-Main-1,5,main]
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at com.terraformersmc.modmenu.util.ModrinthUtil.lambda$checkForUpdates$4(ModrinthUtil.java:86)
	at java.base/java.util.Map.forEach(Map.java:713)
	at com.terraformersmc.modmenu.util.ModrinthUtil.lambda$checkForUpdates$5(ModrinthUtil.java:79)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by drtheodor** [comment]
Huh, need to fix the modmenu integration... Try deleting `server-resource-packs` folder. If the resourcepack got somehow corrupted, deleting the folder might solve the issue.

**Comment by OmegaPhoenix637** [comment]
Still getting kicked with the removal of server-resourse-packs

**Comment by drtheodor** [comment]
[rptweaks-1.0.1-1.19.3.jar.zip](https://github.com/DrTheodor/rptweaks/files/12341861/rptweaks-1.0.1-1.19.3.jar.zip)
I wonder if... Try this build (the jar is in the zip file), let me know if it works

**Comment by OmegaPhoenix637** [comment]
It works now thank you so much :D

**Comment by drtheodor** [comment]
Gonna get the patched version on modrinth tomorrow :D

**Comment by drtheodor** [comment]
Whoops, completely forgot about this, uhhh
I'll update modrinth soon

**Comment by drtheodor** [comment]
@OmegaPhoenix637 I'd recommend to re-download the mod from [the modrinth page](https://modrinth.com/mod/resource-pack-tweaks). I fixed the mod menu integration in the release as well.

**Comment by OmegaPhoenix637** [comment]
Okay thank you
